a = 2
print(a)

#> BƯỚC 01: DI CHUYỂN VÀO THƯ MỤC CHỨA TẬP TIN PYTHON, BẠN CẦN SỬ DỤNG ĐƯỜNG DẪN ĐẾN THƯ MỤC
	#+ TRONG TERMINAL GÕ 'CD .\DATASTRUCTUREANDALGORITHMS_CYBERSOFT\#01 - IN CLASS CODE\BUOI_03_SYNTAX_PYTHON\' 
		#? LƯU Ý 01: CÓ THỂ GÕ VÀI CHỮ TÊN FILE RỒI BẤM TAB'
		#? LƯU Ý 02: NẾU PATH CÓ DẤU CÁCH PHẢI ĐỂ PATH TRONG NGOẶC KÉP ''
#> BƯỚC 02: CHẠY TẬP TIN PYTHON
	#+ TRONG TERMINAL GÕ PYTHON + TÊN FILE.PY
	#+ PYTHON Phan_01_Cach_Chay_File_Python.py
	#+ ENTER