
#> 01 - PROGRAMMING LANGUAGE - NGÔN NGỮ LẬP TRÌNH
	#* NGÔN NGỮ LẬP TRÌNH LÀ MỘT HỆ THỐNG KÝ HIỆU ĐƯỢC SỬ DỤNG ĐỂ VIẾT CÁC CHƯƠNG TRÌNH PHẦN MỀM.
	#* CÁC CHƯƠNG TRÌNH NÀY ĐIỀU KHIỂN MÁY TÍNH THỰC HIỆN CÁC TÁC VỤ CỤ THỂ.
	#* MỖI NGÔN NGỮ LẬP TRÌNH CÓ CÚ PHÁP VÀ CẤU TRÚC RIÊNG ĐỂ THỂ HIỆN CÁC GIẢI THUẬT VÀ LUỒNG LOGIC CỦA CHƯƠNG TRÌNH.
		#+ PYTHON	: NGÔN NGỮ LẬP TRÌNH ĐA NĂNG, DỄ HỌC, ĐƯỢC SỬ DỤNG NHIỀU TRONG TRÍ TUỆ NHÂN TẠO VÀ KHOA HỌC DỮ LIỆU.
		#+ C++		: NGÔN NGỮ MẠNH MẼ, CÓ CÚ PHÁP PHỨC TẠP HƠN, ĐƯỢC DÙNG CHO PHÁT TRIỂN HỆ THỐNG VÀ PHẦN MỀM HIỆU NĂNG CAO.
#> 02 - HYPERTEXT LANGUAGE - NGÔN NGỮ SIÊU VĂN BẢN
	#* NGÔN NGỮ SIÊU VĂN BẢN THƯỜNG ĐỀ CẬP ĐẾN HTML (HYPERTEXT MARKUP LANGUAGE), ĐƯỢC DÙNG ĐỂ TẠO RA CẤU TRÚC CỦA CÁC TRANG WEB.
	#* HTML KHÔNG PHẢI LÀ NGÔN NGỮ LẬP TRÌNH, MÀ LÀ MỘT NGÔN NGỮ ĐÁNH DẤU ĐỂ XÁC ĐỊNH CẤU TRÚC VÀ CÁCH TRÌNH BÀY NỘI DUNG TRÊN CÁC TRANG WEB.
	#* HTML SỬ DỤNG CÁC THẺ (TAGS) ĐỂ ĐỊNH DẠNG VĂN BẢN, HÌNH ẢNH, LIÊN KẾT, VÀ CÁC YẾU TỐ KHÁC TRONG MỘT TÀI LIỆU.
#> 03 - QUERY LANGUAGE - NGÔN NGỮ TRUY VẤN
	#* NGÔN NGỮ TRUY VẤN ĐƯỢC SỬ DỤNG ĐỂ TƯƠNG TÁC VÀ LẤY DỮ LIỆU TỪ CÁC HỆ QUẢN TRỊ CƠ SỞ DỮ LIỆU.
		#+ SQL (STRUCTURED QUERY LANGUAGE) LÀ NGÔN NGỮ TRUY VẤN PHỔ BIẾN NHẤT, GIÚP NGƯỜI DÙNG THỰC HIỆN CÁC THAO TÁC NHƯ TÌM KIẾM, THÊM, SỬA HOẶC XÓA DỮ LIỆU TRONG CÁC BẢNG CỦA CƠ SỞ DỮ LIỆU.
#> 04 - SCRIPTING LANGUAGE - NGÔN NGỮ KỊCH BẢN
	#* NGÔN NGỮ KỊCH BẢN ĐƯỢC SỬ DỤNG ĐỂ TỰ ĐỘNG HÓA CÁC TÁC VỤ TRONG PHẦN MỀM HOẶC HỆ THỐNG, THƯỜNG DỄ HỌC VÀ KHÔNG CẦN BIÊN DỊCH NHƯ NGÔN NGỮ LẬP TRÌNH TRUYỀN THỐNG.
	#* CÁC NGÔN NGỮ NÀY THƯỜNG ĐƯỢC SỬ DỤNG ĐỂ VIẾT CÁC TẬP LỆNH (SCRIPT) THỰC HIỆN CÁC TÁC VỤ TỰ ĐỘNG TRONG HỆ THỐNG HOẶC TRÊN CÁC TRANG WEB.
		#+ JAVASCRIPT: ĐƯỢC SỬ DỤNG CHỦ YẾU ĐỂ PHÁT TRIỂN CÁC TÍNH NĂNG TƯƠNG TÁC TRÊN TRÌNH DUYỆT WEB.
		#+ PHP: DÙNG TRONG PHÁT TRIỂN WEB PHÍA MÁY CHỦ.
		#+ BASH: NGÔN NGỮ KỊCH BẢN PHỔ BIẾN TRÊN CÁC HỆ ĐIỀU HÀNH UNIX/LINUX.
#> 05 - MARKUP LANGUAGE - NGÔN NGỮ MÔ TẢ
	#* ĐƯỢC SỬ DỤNG ĐỂ XÁC ĐỊNH CẤU TRÚC DỮ LIỆU, CÁCH TRÌNH BÀY THÔNG TIN, HOẶC ĐỊNH NGHĨA TÀI LIỆU.
		#+ XML (EXTENSIBLE MARKUP LANGUAGE): ĐƯỢC SỬ DỤNG ĐỂ LƯU TRỮ VÀ VẬN CHUYỂN DỮ LIỆU DƯỚI DẠNG CÓ CẤU TRÚC.
		#+ MARKDOWN: ĐƯỢC DÙNG ĐỂ ĐỊNH DẠNG VĂN BẢN MỘT CÁCH ĐƠN GIẢN, THƯỜNG THẤY TRONG CÁC NỀN TẢNG VIẾT BLOG, TÀI LIỆU KỸ THUẬT.
#> 06 - FUNCTIONAL PROGRAMMING LANGUAGE - NGÔN NGỮ LẬP TRÌNH HÀM
	#* NGÔN NGỮ LẬP TRÌNH HÀM TẬP TRUNG VÀO VIỆC SỬ DỤNG CÁC HÀM ĐỂ THỰC HIỆN TÍNH TOÁN, THAY VÌ THAO TÁC TRỰC TIẾP TRÊN BIẾN VÀ TRẠNG THÁI.
	#* ĐÂY LÀ MỘT DẠNG LẬP TRÌNH KHÁC BIỆT SO VỚI LẬP TRÌNH HƯỚNG ĐỐI TƯỢNG HOẶC MỆNH LỆNH.
		#+ HASKELL: MỘT NGÔN NGỮ LẬP TRÌNH HÀM MẠNH MẼ, THUẦN TÚY.
		#+ LISP: MỘT TRONG NHỮNG NGÔN NGỮ LẬP TRÌNH HÀM LÂU ĐỜI NHẤT, NỔI TIẾNG VỚI KHẢ NĂNG XỬ LÝ BIỂU THỨC.
#> 07 - LOGIC PROGRAMMING LANGUAGE - NGÔN NGỮ LẬP TRÌNH LOGIC
	#* NGÔN NGỮ LẬP TRÌNH LOGIC KHÔNG DỰA VÀO CÁC BƯỚC THỰC HIỆN NHƯ TRONG CÁC NGÔN NGỮ LẬP TRÌNH MỆNH LỆNH.
	#* THAY VÀO ĐÓ, CHÚNG TẬP TRUNG VÀO CÁC MỆNH ĐỀ VÀ LOGIC TOÁN HỌC ĐỂ MÔ TẢ MỐI QUAN HỆ GIỮA CÁC SỰ KIỆN VÀ DỮ LIỆU.
		#+ PROLOG: MỘT NGÔN NGỮ LẬP TRÌNH LOGIC DÙNG NHIỀU TRONG TRÍ TUỆ NHÂN TẠO VÀ XỬ LÝ NGÔN NGỮ TỰ NHIÊN.
#> 08 - CONTROL LANGUAGE - NGÔN NGỮ ĐIỀU KHIỂN
	#* NGÔN NGỮ ĐIỀU KHIỂN ĐƯỢC SỬ DỤNG ĐỂ ĐIỀU KHIỂN PHẦN CỨNG HOẶC QUẢN LÝ HỆ THỐNG.
	#* GIÚP THỰC HIỆN CÁC TÁC VỤ Ở MỨC THẤP HƠN SO VỚI CÁC NGÔN NGỮ LẬP TRÌNH TRUYỀN THỐNG.
		#+ VHDL (VHSIC HARDWARE DESCRIPTION LANGUAGE): ĐƯỢC SỬ DỤNG ĐỂ MÔ TẢ VÀ LẬP TRÌNH CÁC HỆ THỐNG PHẦN CỨNG, NHƯ CÁC VI MẠCH.
		#+ VERILOG: NGÔN NGỮ LẬP TRÌNH DÀNH CHO THIẾT KẾ HỆ THỐNG ĐIỆN TỬ VÀ KỸ THUẬT SỐ.
#> 09 - STYLE LANGUAGE - NGÔN NGỮ ĐỊNH KIỂU
	#* ĐÂY LÀ NGÔN NGỮ ĐƯỢC SỬ DỤNG ĐỂ ĐỊNH NGHĨA CÁCH TRÌNH BÀY CỦA TÀI LIỆU, THƯỜNG TRONG NGỮ CẢNH WEB HOẶC IN ẤN.
		#+ CSS (CASCADING STYLE SHEETS): ĐƯỢC SỬ DỤNG ĐỂ ĐỊNH DẠNG VÀ BỐ CỤC CÁC TRANG WEB, QUẢN LÝ CÁC YẾU TỐ NHƯ MÀU SẮC, KHOẢNG CÁCH, VÀ BỐ CỤC CỦA TRANG.
#> 10 - SPECIFICATION LANGUAGE - NGÔN NGỮ ĐẶC TẢ
	#* NGÔN NGỮ ĐẶC TẢ ĐƯỢC SỬ DỤNG ĐỂ MÔ TẢ MỘT HỆ THỐNG HOẶC PHẦN MỀM Ở MỨC ĐỘ TRỪU TƯỢNG CAO, THƯỜNG ĐƯỢC SỬ DỤNG TRONG QUÁ TRÌNH PHÂN TÍCH VÀ THIẾT KẾ.
		#+ UML (UNIFIED MODELING LANGUAGE): DÙNG ĐỂ MÔ HÌNH HÓA VÀ ĐẶC TẢ THIẾT KẾ PHẦN MỀM.
#> 11 - SEMI-STRUCTURED QUERY LANGUAGE - NGÔN NGỮ TRUY VẤN DỮ LIỆU BÁN CẤU TRÚC
	#* DÙNG ĐỂ TRUY VẤN CÁC LOẠI DỮ LIỆU KHÔNG HOÀN TOÀN CÓ CẤU TRÚC NHƯ SQL NHƯNG VẪN CẦN TRUY VẤN DỰA TRÊN CÁC ĐỊNH DẠNG NHƯ JSON HAY XML.
		#+ XQUERY: TRUY VẤN DỮ LIỆU TỪ TÀI LIỆU XML.
		#+ SPARQL: MỘT NGÔN NGỮ TRUY VẤN CHO CÁC DỮ LIỆU RDF TRONG HỆ THỐNG WEB NGỮ NGHĨA.
#> 12 - PARALLEL PROGRAMMING LANGUAGE - NGÔN NGỮ LẬP TRÌNH SONG SONG
	#* NGÔN NGỮ NÀY ĐƯỢC SỬ DỤNG ĐỂ VIẾT CÁC CHƯƠNG TRÌNH CÓ THỂ THỰC THI ĐỒNG THỜI NHIỀU TÁC VỤ, GIÚP CẢI THIỆN HIỆU SUẤT TRÊN CÁC HỆ THỐNG ĐA LÕI HOẶC HỆ THỐNG PHÂN TÁN.
		#+ OPENMP: MỘT API SỬ DỤNG TRONG C/C++ VÀ FORTRAN ĐỂ LẬP TRÌNH SONG SONG TRÊN CÁC BỘ XỬ LÝ ĐA LÕI.
#> 13 - DOMAIN-SPECIFIC LANGUAGE - DSL - NGÔN NGỮ MIỀN CHUYÊN BIỆT
	#* DSL LÀ NHỮNG NGÔN NGỮ ĐƯỢC THIẾT KẾ ĐỂ GIẢI QUYẾT CÁC VẤN ĐỀ TRONG MỘT MIỀN CỤ THỂ NÀO ĐÓ, KHÔNG PHẢI NGÔN NGỮ ĐA NĂNG NHƯ PYTHON HAY JAVA.
		#+ SQL: ĐƯỢC THIẾT KẾ CHỈ ĐỂ TƯƠNG TÁC VỚI CƠ SỞ DỮ LIỆU QUAN HỆ.
		#+ REGEX (REGULAR EXPRESSIONS): MỘT DSL CHUYÊN BIỆT CHO VIỆC XỬ LÝ CHUỖI VÀ MẪU KÝ TỰ.